### ISSUE TITLE
Samples not loading in logic pro x

### ISSUE THREAD

**Issue by dicqbeats** [publicsamples/Quetzalcoatl#22] opened 2024-08-10 00:46 UTC
initial samples that came with the install not loading, keeps saying "the sample directory could not be loaded" but everything seemed to unpack just fine. Samples are blacked out when asked to choose sample folder.

**Comment by RickTaylor79** [comment] 2024-08-10 08:54
Did you restart the plugin?

The sample would be blacked out, this because you are selecting a folder, not the samples themselves.

**Comment by akashired** [comment] 2024-08-10 23:59
hey, same issue here

i reloaded the plugin and installed the samples multiple times - it keeps saying that all samples have been successfully installed but when I reload the plugin Im asked to install it all over again

**Comment by RickTaylor79** [comment] 2024-08-11 00:32
Thanks..

Weird, I cannot reproduce this behaviour (Sonoma 14.5), but Logic may be the problem..  Can you share the contents of?: 

~/Library/Application Support/modularsamples/Quetzalcoatl/GeneralSettings.xml

**Comment by akashired** [comment] 2024-08-11 01:20
i have ventura 13.4.1 runing logic 10.7 with rosetta 

Actually this folder doesnt exist, I dont see any modularsamples folder in Application Support

**Comment by RickTaylor79** [comment] 2024-08-11 10:32
Curious. I just fired up logic 11.x on my second machine and still can't reproduce this. 

Can you confirm a couple of things for me please?

1. Are you running the latest version of Quetzalcoatl (0.7.0)?
2. Are you looking at the correct Application Support folder?

There are two Application Support folders on a Mac. One is found at: Macintosh HD/Library/Application Support

And another at: Macintosh HD/Users/yourusername/Library/Application Support/

This folder is hidden by default, and is the location we are interested in. The quickest way to reveal it is by opening Finder, selecting "Go to Folder.. " from the the go menu and enter ~/Library/Application Support/

**Comment by akashired** [comment] 2024-08-12 02:34
1. yes I just downloaded it again to make sure, same issue 
2.  my bad you were right, I found the folder , heres a video screen 

https://github.com/user-attachments/assets/12d3d7ec-1071-40b0-96d7-ceda83b6f0e5

**Comment by RickTaylor79** [comment] 2024-08-12 08:36
Thanks for that. Okay, this is something.. One last thing, could you upload the GeneralSettings.xml & LinkOSX files found in the Quetzalcoatl folder, please? 

GeneralSettings.xml should look like this (the critical part is SAMPLES_FOUND, It _should_ have a value of 1):

`<GLOBAL_SETTINGS DISK_MODE="0" SCALE_FACTOR="1.0" VOICE_AMOUNT_MULTIPLIER="2"
                 MIDI_CHANNELS="1" SAMPLES_FOUND="1" 
				 OPEN_GL="0"/>`

LinkOSX tells the plugin where you installed the samples, mine looks like this:

`/Users/rick/Music/modularsamples/Quetzalcoatl/Samples`

Assuming the LinkOSX file is populated, you might be able to fix it by simply changing SAMPLES_FOUND="0" to SAMPLES_FOUND="1".

**Comment by RickTaylor79** [comment] 2024-08-18 08:05
v0.7.1 comes as an installer package for Mac OS and should resolve any issues with samples, locations and so on. 

https://github.com/publicsamples/Quetzalcoatl/releases/tag/0.7.1

With this in mind, I'm going to close this issue, but feel free to reopen if you are still having problems.

**Closed by RickTaylor79** 2024-08-18 08:05 UTC
